%global tl_name xcjk2uni
%global tl_revision 54958

Name:		texlive-%{tl_name}
Epoch:		1
Version:	1.0
Release:	%{tl_revision}.1
Summary:	Convert CJK characters to Unicode, in pdfTeX
Group:		Publishing
URL:		https://www.ctan.org/tex-archive/macros/latex/contrib/xcjk2uni
License:	lppl1.3c
Source0:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/xcjk2uni.r%{tl_revision}.tar.xz
Source1:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/xcjk2uni.doc.r%{tl_revision}.tar.xz
Source2:	https://mirrors.ctan.org/systems/texlive/tlnet/archive/xcjk2uni.source.r%{tl_revision}.tar.xz
BuildArch:	noarch
BuildSystem:	texlive
Provides:	texlive(%{tl_name}) = %{tl_revision}

%description
The package provides commands to convert CJK characters to Unicode in
non-UTF-8 encoding; it provides hooks to support hyperref in producing
correct bookmarks. The bundle also provides /ToUnicode mapping file(s)
for a CJK subfont; these can be used with the cmap package, allowing
searches of, and cut-and-paste operations on a PDF file generated by
pdfTeX.

